project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!Module1_Part2/HW02/HW02.qmd"
    
website:
  title: "MAS STAT-5101 Statistical Methods"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/logicartis/mas-stat-5101

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true